language: node_js
node_js:
  - "0.11"
  - "0.10"
before_script:
  - npm install
  - npm install -g grunt-cli
  - npm install -g bower
  - gem install jekyll
  - gem install sass
  - bower install
script:
  - grunt test
